version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=YAM428
      - DRUPAL_DATABASE_PASSWORD=30719082
      - DRUPAL_DATABASE_NAME=final

  db:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=YAM428
      - MARIADB_USER=30719082
      - MARIADB_PASSWORD=final

  webserver:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_SERVER_NAME=anilcankirtil.me

  certificate:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/etc/letsencrypt --email testmail@demo.com --agree-tos --no-eff-email --staging --force-renewal

    